/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0a7a4d62-59b4-4e75-aad8-a3d0ae3536fd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yLkM08ZzD",
    "aws_user_pools_web_client_id": "48v9fpc23ldq4jbblkpmddbpmm",
    "oauth": {}
};


export default awsmobile;
